# Build is configured to run both: "Build pushed branches" & "Build pushed pull requests"
# Purpose of having "Build pushed branches" is to run build against master branch every time we merge PR.
# However we don't want to trigger unnecessary build against feature branch when we have PR already opened and we amend feature branch.
# Therefore following rule whitelist "master" branch only.
branches:
  only:
    - "master"

sudo: false

language: go

go:
  - 1.10.x
  - master

env:
  - DEP_VERSION="0.5.0"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

# Skip the install step. Don't `go get` dependencies. Only build with the code in vendor/
install: true

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: master
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

notifications:
  email: false

before_script:
  - make install

script:
  - make static-check
  - make test-with-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -F unit -f coverage.txt
